### ISSUE TITLE
How to reproduce Zero-Shot Voice Conversion samples

### ISSUE THREAD

**Issue by nateraw** [revsic/torch-nansypp#2]
Hey there, was checking out the samples page and was really impressed by the Zero-Shot Voice Conversion results. I know you have a `inference.py` script you're working on, but could you perhaps provide a general/hacky snippet that I can try in the meantime, please?

Thanks so much!

**Comment by revsic** [comment]
Hi, I'm not the author of that paper, this repository is only one of the unofficial implementations. I'm still training the models and I'll upload the inference code near soon. Thanks for your interest.

**Comment by nateraw** [comment]
Oh wow, totally missed that. 🙀 Sorry about that! Thanks for your work on this
