### ISSUE TITLE
Status of the project 

### ISSUE THREAD

**Issue by Ryu1845** [revsic/torch-nansypp#3]
Hi, in #2, you said you were training the model and were going to upload inference code soon. I was wondering how that was going.

**Comment by revsic** [comment]
In recent experiment, I'm fail to reproduce the speech quality compared with the author's one. I'm ablating each modules for checking my implementations now.

**Comment by Ryu1845** [comment]
Thank you for your response and your efforts on this replication.
I'm hoping you'll be able to make it work.

**Comment by talipturkmen** [comment]
Hello, is there any update about the status of the project?

**Comment by revsic** [comment]
@talipturkmen Hi, but there is no other updates in this project. My NANSY++ model works similar as the author's one, but not same and worse. Nevertheless, if you want checkpoints, I have plans to release them.

**Comment by talipturkmen** [comment]
Thank you for the response. It'd be great to have the checkpoints. Related to d_scale in the pitch consitency loss did you use 0.5 as scale or 0.5/12?

**Comment by pcournut** [comment]
Thanks for the implementation @revsic. We’ve built [our own](https://github.com/MWM-io/nansypp) (backbone and TTS) on top of it in my team and ran some experiments lately, trying to replicate the paper. Any discussion and collaboration is welcome!
